### ISSUE TITLE
Provide TypeScript types

### ISSUE THREAD

**Issue by charlax** [TwicPics/react#3]
Thanks for this lib! Would you mind adding types?

**Comment by florentb** [comment]
Sure @charlax. This is the next step.

**Comment by Aarbel** [comment]
@florentb any news about that ?

**Comment by florentb** [comment]
Currently working on a major refactoring which you can find [here](https://github.com/TwicPics/components) if you want to have a look. Not documented yet.

**Comment by Aarbel** [comment]
Looks great, any plan for release date ?

**Comment by florentb** [comment]
Hi guys! 

**[Twicpics Components](https://github.com/TwicPics/components)** has been released. 
Same features, common codebase for all frameworks, TypeScript rewriting, ...

👉 [Check the documentation](https://github.com/TwicPics/components/tree/main/documentation)

As a result, this package is no longer supported and we encourage you to make the switch. 

See you there 😉
