### ISSUE TITLE
Chrome 53 support 

### ISSUE THREAD

**Issue by meyer59** [TwicPics/react#4]
Hello
We have an end client who use your plateform to integrate images on his website.
This website is runing on an old device with chrome v53.
The problem we are facing is that images are not loading.
I thing we need a polyfil to run your script but i cannot find wich one.
The client use your library to load image (https://www.twicpics.com/docs/script/setup)
After investigating it seems like
all the data-* atribute are set to the <img/> tag. 
But your library is unable to provide the img src attribute and do the transormation, thats why the image is not showing.
Since your script is minified, it is difficult to investigate. 
We will really appreciate your help here.
Thanks in advance

**Comment by jaubourg** [comment]
@meyer59 I see you closed the issue. Did you resolve it or do you need more help?

**Comment by meyer59** [comment]
I closed the issue because i contacted the support through your website and they told me they will check it up. It seems like a duplicate support ticket so i closed up. Feel free to reopen it. Once i’ll have the solution i will post it up here.
